name: audio_player
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  adaptive_breakpoints: ^0.1.6
  adaptive_components: ^0.0.9
  adaptive_navigation: ^0.0.9
  animations: ^2.0.8
  collection: ^1.17.2
  desktop_window: ^0.4.0
  dynamic_color: ^1.6.8
  english_words: ^4.0.0
  go_router: ^12.0.0
  google_fonts: ^6.1.0
  material_color_utilities: ^0.5.0
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.14
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/playlists/
    - assets/images/albums/
    - assets/images/artists/
    - assets/images/news/