name: riverwave_music_player
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  adaptive_breakpoints: ^0.1.7
  adaptive_components: ^0.0.10
  adaptive_navigation: ^0.0.10
  animations: ^2.0.11
  collection: ^1.18.0
  desktop_window: ^0.4.0
  dynamic_color: ^1.7.0
  english_words: ^4.0.0
  go_router: ^13.2.2
  google_fonts: ^6.2.1
  material_color_utilities: ^0.8.0
  universal_platform: ^1.0.0+1
  url_launcher: ^6.2.5
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/playlists/
    - assets/images/albums/
    - assets/images/artists/
    - assets/images/news/